<a href="https://colab.research.google.com/github/AbeChessell/AbeChessell-Programming-BigDataAnalytics/blob/main/2_01_introduction_to_pandasCOMPLETED.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![](https://drive.google.com/uc?export=view&id=1vv_PsWBnUJwSCkwKDoJAC-vXjtaEA4Ts)

# Introduction to Pandas

### What is Pandas?
As Python has grown to become a popular solution for data analysis, many new tools have been introduced to support such tasks. Pandas is arguably the most popular and widely used of these, although it does have some limitations (if working with very large datasets you may want to look at Dask and/or PySpark).

First, we will import it into our session. We will also import numpy - another widely used Python package for working with numerical data (the name is a portmanteau of "numerical" and "python"). By convention we import pandas as "pd" and numpy as "np". This is equivalent to giving it a variable name.

In [ ]:
import pandas as pd
import numpy as np

### Testing our installation
To test everything is working we will create some fake data frame using numpy and load it into a pandas dataframe (more on these below). First we will create the random numbers:

In [ ]:
x = np.random.rand(10,1)
x

array([[0.37014973],
       [0.55018948],
       [0.60983401],
       [0.92435003],
       [0.07061554],
       [0.37247295],
       [0.40341851],
       [0.1259233 ],
       [0.9757731 ],
       [0.53536077]])

The commands here have told numpy to create a set of random numbers between zero and one. The arguments we have passed, "1" and "10", tells numpy we want a 10x1 array of numbers (i.e. a vector).

Next we will create a pandas dataframe using "x":

In [ ]:
testdf = pd.DataFrame(x)
testdf

          0
0  0.370150
1  0.550189
2  0.609834
3  0.924350
4  0.070616
5  0.372473
6  0.403419
7  0.125923
8  0.975773
9  0.535361

We have now successfully created a pandas dataframe!

### What are Dataframes?
Pandas has a very elegant way of managing data, very much borrowed from the statistical language R, mostly based around dataframes. You can think of dataframes a bit like an Excel table with rows, columns and common operations like sum, average and so on. We can use this on top of our previous work on lists and dictionaries (etc.) more usable and malleable.

To begin with we will create a dataset - in this case a dictionary.

In [ ]:
orders = {'o10001':{'date':'2025/01/10', 'product':'Blockchain database', 'quantity':'1'},
            'o10002':{'date':'2025/01/13', 'product':'Stock market prediction engine', 'quantity':'2'},
            'o10003':{'date':'2025/01/14', 'product':'Portfolio optimisation tool', 'quantity':'10'},
            'o10004':{'date':'2025/01/15', 'product':'Man\'s suit', 'quantity':'2'}
}
orders

{'o10001': {'date': '2025/01/10',
  'product': 'Blockchain database',
  'quantity': '1'},
 'o10002': {'date': '2025/01/13',
  'product': 'Stock market prediction engine',
  'quantity': '2'},
 'o10003': {'date': '2025/01/14',
  'product': 'Portfolio optimisation tool',
  'quantity': '10'},
 'o10004': {'date': '2025/01/15', 'product': "Man's suit", 'quantity': '2'}}

We can convert this to a Dataframe with great ease

In [ ]:
import pandas as pd
import numpy as np

orders_df = pd.DataFrame(orders)
orders_df

,o10001,o10002,o10003,o10004
date,2025/01/10,2025/01/13,2025/01/14,2025/01/15
product,Blockchain database,Stock market prediction engine,Portfolio optimisation tool,Man's suit
quantity,1,2,10,2

We can even create such outputs from more complex dictionaries, such as a dictionary which includes a nested list:

In [ ]:
customers = {'Siamak':{'name':'Siamak Naderi', 'open_orders':3, 'orders':['o10001', 'o10002', 'o10004']},
             'Ram':{'name':'Ram Gopal', 'open_orders':0, 'orders':[]},
             'Moris':{'name':'Moris Strub', 'open_orders':1, 'orders':['o10003']},
             'Ephie':{'name':'Ephie Wang', 'open_orders':0, 'orders':[]}
}
customers

{'Siamak': {'name': 'Siamak Naderi',
  'open_orders': 3,
  'orders': ['o10001', 'o10002', 'o10004']},
 'Ram': {'name': 'Ram Gopal', 'open_orders': 0, 'orders': []},
 'Moris': {'name': 'Moris Strub', 'open_orders': 1, 'orders': ['o10003']},
 'Ephie': {'name': 'Ephie Wang', 'open_orders': 0, 'orders': []}}

In [ ]:
customers_df = pd.DataFrame(customers)
customers_df

                               Siamak        Ram        Moris       Ephie
name                    Siamak Naderi  Ram Gopal  Moris Strub  Ephie Wang
open_orders                         3          0            1           0
orders       [o10001, o10002, o10004]         []     [o10003]          []

Pandas dataframes can also be built from various other data structures and sources (including Excel files, CSVs, text files, databases and many more). To conclude the session we will look at a list example:

In [ ]:
a = [1, 2, 3, 4]
b = ["a", "b", "c", "d"]
c = [True, False, True, False]

listdf = pd.DataFrame([a, b, c])
listdf

      0      1     2      3
0     1      2     3      4
1     a      b     c      d
2  True  False  True  False

### EXERCISE
Try building you own dataframes from a list and/or dictionary you create. What would happen if you have an item missing from one element. E.g. if "c" in the above example only had three items - True, False, True - rather than four. Test it - does the output match your expectation?

In [ ]:
import pandas as pd

height = [1.75, 1.84, 1.76,1.98, 1.67 , 1.48]
weight = [68, 80, 72, 95, 69, 55]
df = pd. DataFrame([height,weight])
df.columns = ['Person 1', 'Person 2', 'Person 3', 'Person 4', 'Person 5', 'Person 6']
df.index = ['height', 'weight']
df.loc['bmi'] = df.loc['weight']/ df.loc['height']**2
df

         Person 1  Person 2   Person 3   Person 4   Person 5   Person 6
height   1.750000   1.84000   1.760000   1.980000   1.670000   1.480000
weight  68.000000  80.00000  72.000000  95.000000  69.000000  55.000000
bmi     22.204082  23.62949  23.243802  24.232221  24.740937  25.109569

In [ ]:
a = [1,2,3,4]
b= ['a','b','c','d']
c = [True, False, True]

list2df = pd.DataFrame([a,b,c])
list2df #should return a none value

      0      1     2     3
0     1      2     3     4
1     a      b     c     d
2  True  False  True  None